name: Pipeline CI/CD - Catálogo de Jogos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Define que os comandos vão rodar dentro da pasta do projeto React
    defaults:
      run:
        working-directory: ./catalogo-jogos

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./catalogo-jogos/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Lint
        run: npm run lint

      - name: Rodar Testes
        run: npm run test

      - name: Build do projeto
        run: npm run build
        env:
          VITE_RAWG_API_KEY: ${{ secrets.VITE_RAWG_API_KEY }}

      - name: Upload do artefato para Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: './catalogo-jogos/dist'

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4